import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export type Language = 'es' | 'en'

const translations: Record<string, string> = {
  'Inicio': 'Home',
  'Nosotros': 'About Us',
  'Contáctanos': 'Contact Us',
  'Donar Ahora': 'Donate Now',
  'Donación': 'Donate',
  'DONACIÓN': 'DONATE',
  'VOLUNTARIADO': 'VOLUNTEER',
  'ALIANZAS': 'PARTNERSHIPS',
  'MEMBRESIAS': 'MEMBERSHIP',
  'INICIO': 'HOME',
  'NOSOTROS': 'ABOUT US',
  'DONACIONES': 'DONATIONS',
  'Cerrar menú': 'Close menu',
  'Abrir menú': 'Open menu',
  'Cerrar búsqueda': 'Close search',
  'Idioma: español': 'Language: English',
  'Idioma: inglés': 'Language: Spanish',
  'Redes sociales': 'Social media',
  'SOMOS': 'WE ARE',
  '¿QUÉ HACEMOS?': 'WHAT WE DO',
  'CONÓCENOS': 'ABOUT US',
  'Trabajamos junto a comunades de la Amazonía y los Andes para construir sostenible': 'We work with communities in the Amazon and Andes to build a sustainable future.',
  'Sembrando Perú es una organización sin fines de lucro comprometida con la protección de la Amazonía peruana y el desarrollo sostenible de las comunidades rurales.': 'Sembrando Perú is a nonprofit organization committed to protecting the Peruvian Amazon and promoting the sustainable development of rural communities.',
  'Restauramos bosques degradados, promovemos la educación y la alfabetización, fortalecemos la salud infantil y combatimos la anemia en las zonas más vulnerables del país.': 'We restore degraded forests, promote education and literacy, strengthen child health, and combat anemia in the most vulnerable areas of the country.',
  'Fotografías de nuestras actividades': 'Photographs of our activities',
  'Mejorando vida, futuro y medio ambiente': 'Improving lives, futures, and the environment',
  'Trabajamos por un futuro sostenible desde diferentes frentes.': 'We work toward a sustainable future on several fronts.',
  'NUESTRO TRABAJO': 'OUR WORK',
  'Medio ambiente': 'Environment',
  'Filtrar iniciativas por categoría': 'Filter initiatives by category',
  'SEMBRANDO ÁRBOLES': 'PLANTING TREES',
  'SEMBRANDO EDUCACIÓN': 'PLANTING EDUCATION',
  'SEMBRANDO SALUD': 'PLANTING HEALTH',
  'Trabajamos para restaurar los árboles extraídos de manera injusta en la Amazonía, protegiendo bosques y la biodiversidad.': 'We restore trees unjustly removed from the Amazon, protecting forests and biodiversity.',
  'Promovemos la igualdad social a través de procesos de alfabetización.': 'We promote social equality through literacy programs.',
  'Trabajamos para prevenir la anemia infantil en niños de las regiones de Selva y Sierra, mejorando su salud y bienestar.': 'We work to prevent childhood anemia in the Jungle and Highlands regions, improving children’s health and well-being.',
  'Apoya esta iniciativa': 'Support this initiative',
  'Últimas noticias': 'Latest news',
  'Ver más': 'See more',
  'Leer artículo': 'Read article',
  'Leer más': 'Read more',
  'MEDIO AMBIENTE': 'ENVIRONMENT',
  'COMUNIDAD': 'COMMUNITY',
  'Sembrando futuro: juntos por nuestros bosque': 'Growing a future together for our forests',
  'Conoce nuestras acciones de reforestación y el impacto que generamos en las comunidades.': 'Learn about our reforestation work and the impact we make in communities.',
  'Convocatoria de voluntariado 2026': '2026 Volunteer Opportunities',
  'Sé parte del cambio y únete a nuestras próximas actividades y proyectos sociales.': 'Be part of the change and join our upcoming activities and community projects.',
  'Transformando vidas en nuestras comunidades': 'Transforming lives in our communities',
  'Conoce las historias y acciones que impulsamos para mejorar la vida de niños y familias.': 'Discover the stories and work helping improve the lives of children and families.',
  'Nombre': 'Name',
  'Apellido': 'Last name',
  'Correo electrónico': 'Email',
  '(Requerido)': '(Required)',
  'País/Región': 'Country/Region',
  'Seleccione país o región*': 'Select country or region*',
  'Otro': 'Other',
  'Quiero recibir noticias por correo sobre proyectos de siembra, avances de impacto y eventos de voluntariado de Sembrando Perú. (Requerido)': 'I would like to receive email updates about planting projects, impact progress, and Sembrando Perú volunteer events. (Required)',
  'Unirme al cambio': 'Join the change',
  'Gracias por unirte a nuestra comunidad.': 'Thank you for joining our community.',
  'Recibe avances mensuales sobre nuestras jornadas de plantación, historias de impacto en nuestras comunidades y noticias sobre cómo estamos protegiendo nuestros ecosistemas.': 'Get monthly updates on our planting work, community impact stories, and news about how we are protecting our ecosystems.',
  'ÚNETE A LA COMUNIDAD': 'JOIN THE COMMUNITY',
  'EN PERÚ:': 'IN PERU:',
  'Oficina Lima (sede principal)': 'Lima Office (headquarters)',
  'Oficina Madre de Dios': 'Madre de Dios Office',
  'Tel: +51 921 462 828': 'Phone: +51 921 462 828',
  'Suscríbete a nuestro boletín': 'Subscribe to our newsletter',
  '¿QUIÉNES SOMOS?': 'WHO WE ARE',
  'Una familia comprometida con la vida, bosques y la Amazonía, creando un futuro sostenible': 'A family committed to life, forests, and the Amazon, building a sustainable future',
  'Nos enfocamos en frenar la tala indiscriminada, combatir el analfabetismo y la anemia infantil en zonas rurales. Trabajamos con comunidades rurales de la Amazonía y Andes, restaurando ecosistemas, mejorando la vida de niños y promoviendo agricultura y salud sostenible.': 'We work to stop illegal logging and fight illiteracy and childhood anemia in rural areas. Together with communities in the Amazon and Andes, we restore ecosystems, improve children’s lives, and promote sustainable agriculture and health.',
  'Nuestra historia': 'Our story',
  'Sembrando Perú nació con una misión clara y profundamente social: mitigar la deforestación, contribuir a la mejora de la educación en zonas rurales y apoyar la lucha contra la anemia infantil en las comunidades más vulnerables del país. Su creación surge como respuesta a la creciente degradación de los bosques nativos, la falta de acceso a educación de calidad y los graves problemas de salud que afectan a miles de niños en áreas rurales y altoandinas.': 'Sembrando Perú was founded with a clear social mission: to reduce deforestation, improve education in rural areas, and help fight childhood anemia in the country’s most vulnerable communities. It was created in response to the growing degradation of native forests, limited access to quality education, and serious health issues affecting thousands of children in rural and high-Andean areas.',
  'Desde sus inicios, Sembrando Perú ha trabajado con un enfoque integral de desarrollo sostenible, entendiendo que la protección del medio ambiente y el bienestar humano están estrechamente conectados. Por ello, la organización impulsa acciones que combinan reforestación, educación ambiental, alfabetización y prevención en salud, trabajando de manera directa y participativa con agricultores, familias y comunidades locales.': 'From the beginning, Sembrando Perú has taken an integrated approach to sustainable development, recognizing that environmental protection and human well-being are closely connected. The organization combines reforestation, environmental education, literacy, and preventive health work, partnering directly with farmers, families, and local communities.',
  'Misión': 'Mission',
  'Reducción de la deforestación en Perú, fomento de la alfabetización en zonas rurales y lucha contra la anemia infantil mediante soluciones sostenibles y educativas.': 'Reduce deforestation in Peru, promote literacy in rural areas, and fight childhood anemia through sustainable, educational solutions.',
  'Visión': 'Vision',
  'Convertirnos en un motor de cambio en la Amazonía y las zonas rurales, donde los árboles restauren los ecosistemas y las nuevas generaciones crezcan sanas y con acceso a una educación de calidad.': 'Become a force for change in the Amazon and rural areas, where trees restore ecosystems and future generations grow up healthy with access to quality education.',
  'Valores': 'Values',
  'SOSTENIBILIDAD': 'SUSTAINABILITY',
  'COMPROMISO SOCIAL': 'SOCIAL COMMITMENT',
  'INNOVACIÓN': 'INNOVATION',
  'Compromiso con el uso responsable de los recursos naturales, promoviendo soluciones que respeten el equilibrio ecológico y favorezcan la conservación a largo plazo.': 'We use natural resources responsibly and promote solutions that respect ecological balance and support long-term conservation.',
  'Prioridad en la mejora de la calidad de vida de las comunidades rurales, centrándose en soluciones que aborden la educación, la salud y el bienestar de las personas más vulnerables.': 'We prioritize quality of life in rural communities, focusing on education, health, and the well-being of people most at risk.',
  'Apertura a nuevas ideas y métodos creativos para resolver problemas medioambientales, educativos y sanitarios, buscando soluciones prácticas y eficaces como el uso de contenedores o cajas de semillas.': 'We welcome creative ideas and methods to address environmental, educational, and health challenges, seeking practical solutions such as seed containers and boxes.',
  'HAGAMOS EL CAMBIO POSIBLE!': 'LET’S MAKE CHANGE POSSIBLE!',
  'Esperanza para un futuro mejor': 'Hope for a better future',
  'Navegación': 'Navigation',
  'Contacto': 'Contact',
  'Involúcrate': 'Get involved',
  'SÍGUENOS :': 'FOLLOW US:',
  '© 2026 Sembrando. Todos los derechos reservados.': '© 2026 Sembrando. All rights reserved.',
  'Políticas de privacidad': 'Privacy Policy',
  'Reforestación': 'Reforestation',
  'Educación': 'Education',
  'Voluntariado': 'Volunteering',
  'Salud': 'Health',
  'Jornada de reforestación en Madre de Dios': 'Reforestation day in Madre de Dios',
  'Un fin de semana lleno de esfuerzo y esperanza, donde más de 50 voluntarios se unieron para restaurar áreas.': 'A weekend of hard work and hope, as more than 50 volunteers joined to restore degraded areas.',
  'Guardianas del bosque: historias locales': 'Guardians of the forest: local stories',
  'Conoce a las mujeres que lideran los esfuerzos de conservación y educación ambiental en sus propias comunidades.': 'Meet the women leading conservation and environmental education efforts in their communities.',
  'Prevención de anemia: nuevos enfoques': 'Anemia prevention: new approaches',
  'Nuestra reciente campaña médica ha introducido métodos innovadores para combatir la malnutrición infantil.': 'Our recent health campaign introduced new approaches to address childhood malnutrition.',
  'Destacados': 'Featured',
  'Últimos Artículos': 'Latest Articles',
  'Limpiar filtro': 'Clear filter',
  'Cargar más historias': 'Load more stories',
  'No hay artículos para este filtro.': 'There are no articles for this filter.',
  'Explorar artículos': 'Explore articles',
  'Categorías': 'Categories',
  'Post más leídos': 'Most read posts',
  'Etiquetas Populares': 'Popular tags',
  '5 consejos para proteger el bosque amazónico': '5 tips to protect the Amazon forest',
  'El rol de la comunidad en la conservación': 'The community’s role in conservation',
  'Lucha contra la prevención de la anemia': 'Fighting anemia',
  'Amazonía': 'Amazon',
  'Sostenibilidad': 'Sustainability',
  'Innovación': 'Innovation',
  'Perú': 'Peru',
  'Clima': 'Climate',
  'Biodiversidad': 'Biodiversity',
  'No hay más historias por ahora.': 'There are no more stories right now.',
  'COMUNÍCATE CON NOSOTROS': 'GET IN TOUCH',
  'Completa el': 'Complete the',
  'siguiente formulario': 'following form',
  'Correo': 'Email',
  'Teléfono': 'Phone',
  'País': 'Country',
  'Ciudad': 'City',
  'Seleccione': 'Select',
  'Número de personas asistentes (Opcional)': 'Number of attendees (Optional)',
  'Número de personas asistentes': 'Number of attendees',
  'Zona donde está tu empresa (Opcional)': 'Where your company is located (Optional)',
  'Zona donde está tu empresa': 'Where your company is located',
  'Mensaje': 'Message',
  'Contactarme por Whatsapp': 'Contact me on WhatsApp',
  'Acepto políticas de privacidad de datos': 'I accept the data privacy policy',
  'Enviar': 'Send',
  'Gracias. Recibimos tu mensaje.': 'Thank you. We received your message.',
  'EN PERÚ:': 'IN PERU:',
  'Oficina Lima (sede principal)': 'Lima Office (headquarters)',
  'EN REDES SOCIALES': 'ON SOCIAL MEDIA',
  'TU CONTRIBUCIÓN': 'YOUR CONTRIBUTION',
  'Frecuencia de donación': 'Donation frequency',
  'Mensual': 'Monthly',
  'Única': 'One-time',
  'Elige el monto': 'Choose an amount',
  'Otro monto': 'Other amount',
  'Otro monto en soles': 'Other amount in soles',
  'Métodos de pago': 'Payment methods',
  'Donar con PayPal': 'Donate with PayPal',
  'Donar con tarjeta de crédito o de débito': 'Donate with a credit or debit card',
  'Próximamente': 'Coming soon',
  'DONAR': 'DONATE',
  'Tu aporte transforma vidas y protege nuestros bosques.': 'Your contribution transforms lives and protects our forests.',
  'ÚNETE AL CAMBIO,': 'JOIN THE CHANGE,',
  'DONA HOY!': 'DONATE TODAY!',
  'SEMBREMOS UN FUTURO SOSTENIBLE PARA EL PERÚ': 'LET US PLANT A SUSTAINABLE FUTURE FOR PERU',
  'PREGUNTAS FRECUENTES': 'FREQUENTLY ASKED QUESTIONS',
  'Ver más preguntas': 'See more questions',
  '¿POR QUÉ DONAR A SEMBRANDO PERÚ?': 'WHY DONATE TO SEMBRANDO PERÚ?',
  '¿CÓMO CONTRIBUYES CON TU DONACIÓN A SEMBRANDO PERÚ?': 'HOW DOES YOUR DONATION HELP SEMBRANDO PERÚ?',
  'Tu donación hace posible más acciones de reforestación, educación y desarrollo sostenible en las comunidades del Perú.': 'Your donation makes more reforestation, education, and sustainable community development possible across Peru.',
  'Tu donación se destina directamente a nuestras jornadas de reforestación, la producción de plantines en viveros y talleres de educación ambiental. Cada aporte asegura la transparencia y continuidad de nuestros proyectos en las comunidades.': 'Your donation directly supports reforestation days, seedling production in nurseries, and environmental education workshops. Each contribution helps keep our community projects transparent and sustainable.',
  'Juntos hacemos crecer oportunidades, recuperamos ecosistemas y construimos un futuro sostenible para el Perú.': 'Together, we grow opportunities, restore ecosystems, and build a sustainable future for Peru.',
  'Tus aportes impulsan el trabajo integral de Sembrando Perú, promoviendo iniciativas ecológicas y comunitarias en nuestras regiones clave.': 'Your contributions support Sembrando Perú’s holistic work, advancing environmental and community initiatives in key regions.',
  'Sembrando Perú trabaja para proteger y recuperar nuestros bosques, fortalecer a las comunidades mediante la reforestación, la educación ambiental y el fortalecimiento de las capacidades locales. Tu donación financia directamente la siembra de árboles, el mantenimiento de viveros y el desarrollo de un entorno más verde y saludable para todos.': 'Sembrando Perú works to protect and restore forests and strengthen communities through reforestation, environmental education, and local capacity building. Your donation directly funds tree planting, nursery maintenance, and a greener, healthier environment for everyone.',
  '¿Cómo se usa mi donación para hacer una diferencia?': 'How does my donation make a difference?',
  'Tu aporte ayuda a financiar directamente nuestras jornadas de reforestación, educación ambiental y trabajo comunitario en la Amazonía peruana.': 'Your contribution directly supports reforestation, environmental education, and community work in the Peruvian Amazon.',
  '¿Cómo se utilizan los fondos de manera eficiente?': 'How are funds used effectively?',
  'Cada contribución se destina a los programas y actividades de Sembrando Perú, con seguimiento y evaluación de nuestros proyectos.': 'Every contribution supports Sembrando Perú programs and activities, with ongoing project monitoring and evaluation.',
  '¿El proyecto tiene beneficios para mí?': 'Does this project benefit me?',
  'Tu donación contribuye a mejorar el futuro de las comunidades y los ecosistemas. Te mantendremos al tanto de los avances e impacto.': 'Your donation helps improve the future of communities and ecosystems. We will keep you updated on our progress and impact.',
  '¿Sembrando Perú ofrece beneficios fiscales para mi aporte?': 'Does Sembrando Perú offer tax benefits for my contribution?',
  'Para consultar sobre comprobantes y beneficios aplicables, escríbenos a contacto@sembrandoperu.org.': 'For information about receipts and applicable benefits, contact us at contacto@sembrandoperu.org.',
  'REFORESTACIÓN Y RESTAURACIÓN ECOLÓGICA': 'REFORESTATION AND ECOLOGICAL RESTORATION',
  'Restauramos los bosques amazónicos con especies nativas y protegemos la biodiversidad de nuestro territorio.': 'We restore Amazon forests with native species and protect the biodiversity of our region.',
  'CONSERVACIÓN DE BIODIVERSIDAD Y FAUNA NATIVA': 'BIODIVERSITY AND NATIVE WILDLIFE CONSERVATION',
  'Promovemos la conservación de los ecosistemas y de las especies que habitan nuestros bosques.': 'We promote the conservation of ecosystems and the species that inhabit our forests.',
  'EDUCACIÓN Y CONCIENCIA AMBIENTAL': 'ENVIRONMENTAL EDUCATION AND AWARENESS',
  'Impulsamos aprendizajes que fortalecen el cuidado del ambiente y crean nuevas oportunidades.': 'We foster learning that strengthens environmental care and creates new opportunities.',
  'SALUD Y BIENESTAR EN COMUNIDADES': 'COMMUNITY HEALTH AND WELL-BEING',
  'Acompañamos a familias con iniciativas de salud, nutrición y desarrollo comunitario.': 'We support families through health, nutrition, and community development initiatives.',
  'Otra': 'Other',
  'Transparencia': 'Transparency',
  'Tel: +51 921 462 828': 'Phone: +51 921 462 828',
  '← Volver a Últimos artículos': '← Back to Latest Articles',
  'Volver a Últimos artículos': 'Back to Latest Articles',
  'Artículos relacionados': 'Related articles',
  'Artículo no encontrado': 'Article not found',
  'Leer': 'Read',
  'Recuperar un bosque es un trabajo colectivo que comienza con una semilla y crece con el compromiso de quienes habitan y cuidan el territorio. En Sembrando Perú impulsamos acciones de reforestación junto a las comunidades para proteger la Amazonía y su biodiversidad.': 'Restoring a forest is a collective effort that begins with a seed and grows through the commitment of the people who live in and care for the land. Sembrando Perú works with communities to protect the Amazon and its biodiversity.',
  'Restaurar con especies nativas': 'Restore with native species',
  'Cada jornada parte de conocer el lugar: sus suelos, sus fuentes de agua y las especies que forman parte del ecosistema. La elección de plantas nativas ayuda a que la restauración responda a las condiciones locales y contribuya a recuperar hábitats.': 'Each effort begins by understanding the land, its soil, water sources, and the species in its ecosystem. Native plants help restoration respond to local conditions and recover habitats.',
  'La producción de plantines y el trabajo en viveros permiten acompañar el proceso desde sus primeras etapas. Familias y voluntarios preparan el terreno y plantan con cuidado, fortaleciendo también el conocimiento compartido sobre el bosque.': 'Seedling production and nursery work support the process from its earliest stages. Families and volunteers prepare the land and plant with care, sharing knowledge about the forest along the way.',
  'Cuidar el bosque después de plantar': 'Care for the forest after planting',
  'La siembra es el comienzo, no el final. El mantenimiento, el monitoreo y la protección de los plantones son necesarios para que puedan desarrollarse y formar parte de un bosque saludable.': 'Planting is the beginning, not the end. Seedlings need maintenance, monitoring, and protection to grow into a healthy forest.',
  'Con la participación de las comunidades, cada acción suma a un objetivo común: conservar la biodiversidad, cuidar los recursos naturales y dejar un entorno más sostenible para las próximas generaciones.': 'With community participation, every action contributes to a shared goal: conserving biodiversity, caring for natural resources, and leaving a more sustainable environment for future generations.',
  'El desarrollo sostenible se construye escuchando a las comunidades y trabajando junto a ellas. Las iniciativas de Sembrando Perú buscan fortalecer capacidades locales y acompañar proyectos que respondan a las prioridades de cada territorio.': 'Sustainable development is built by listening to communities and working alongside them. Sembrando Perú initiatives strengthen local capacity and support projects that respond to each territory’s priorities.',
  'Proyectos que nacen del trabajo conjunto': 'Projects built through collaboration',
  'La colaboración con familias, líderes y organizaciones locales permite reconocer los retos y oportunidades de cada comunidad. A partir de ese diálogo, se impulsan acciones relacionadas con el cuidado ambiental, la educación y el bienestar.': 'Collaboration with families, leaders, and local organizations helps identify each community’s challenges and opportunities. This dialogue leads to action in environmental care, education, and well-being.',
  'Los espacios de aprendizaje e intercambio ayudan a que las personas compartan sus experiencias, desarrollen nuevas habilidades y participen activamente en las decisiones que afectan su entorno.': 'Learning and exchange spaces help people share experiences, develop skills, and take part in decisions that affect their environment.',
  'Oportunidades para crecer en comunidad': 'Opportunities to grow together',
  'Fortalecer capacidades locales significa acompañar procesos que puedan continuar en el tiempo. La educación ambiental, la organización comunitaria y el cuidado de la salud contribuyen a crear mejores oportunidades para niñas, niños y familias.': 'Strengthening local capacity means supporting processes that can continue over time. Environmental education, community organization, and health initiatives create better opportunities for children and families.',
  'Cada avance es resultado de la colaboración. Al unir conocimientos y esfuerzos, las comunidades pueden proteger sus ecosistemas y construir un futuro con más bienestar y posibilidades.': 'Every step forward comes from collaboration. By sharing knowledge and effort, communities can protect ecosystems and build a future with greater well-being and opportunity.',
  'Un fin de semana lleno de esfuerzo y esperanza reunió a voluntarios y familias de Madre de Dios para recuperar espacios degradados y fortalecer el vínculo de la comunidad con su bosque.': 'A weekend of hard work and hope brought volunteers and families in Madre de Dios together to restore degraded areas and strengthen the community’s connection to its forest.',
  'Sembrar en comunidad': 'Planting together',
  'La jornada comenzó con el reconocimiento del terreno y la selección de especies nativas adecuadas para las condiciones locales. Vecinas, vecinos y voluntarios trabajaron en equipo para preparar cada espacio y plantar nuevos árboles.': 'The day began with a survey of the land and selection of native species suited to local conditions. Neighbors and volunteers worked together to prepare each area and plant new trees.',
  'Cada plantón representa un compromiso compartido: cuidar el suelo, proteger las fuentes de agua y recuperar poco a poco el hábitat de numerosas especies.': 'Each seedling represents a shared commitment to care for the soil, protect water sources, and gradually restore habitats for many species.',
  'Un compromiso que continúa': 'A commitment that continues',
  'La reforestación no termina al colocar una planta en la tierra. El seguimiento, el riego y el mantenimiento de los plantones son fundamentales para que puedan crecer y adaptarse.': 'Reforestation does not end when a plant goes into the ground. Monitoring, watering, and maintaining seedlings are essential for their growth and adaptation.',
  'Por eso, el equipo coordina con las familias y organizaciones locales las próximas visitas de monitoreo. Así, el esfuerzo de la jornada se convierte en un proceso duradero de restauración.': 'That is why the team coordinates follow-up visits with local families and organizations, turning the day’s effort into a lasting restoration process.',
  'En distintas comunidades amazónicas, mujeres lideran iniciativas que cuidan el bosque y comparten conocimientos esenciales para las nuevas generaciones.': 'Across Amazonian communities, women lead forest-care initiatives and share essential knowledge with future generations.',
  'Conocimiento que nace del territorio': 'Knowledge rooted in the land',
  'Su trabajo reúne experiencia local, observación de los ciclos naturales y una profunda relación con el territorio. Desde los viveros hasta las actividades educativas, cada acción transmite prácticas de cuidado y colaboración.': 'Their work brings together local experience, observation of natural cycles, and a deep connection to the land. From nurseries to educational activities, each effort passes on practices of care and collaboration.',
  'Las guardianas impulsan espacios donde niñas, niños y jóvenes pueden aprender sobre especies nativas, biodiversidad y el valor de conservar los ecosistemas que sostienen la vida comunitaria.': 'These guardians create spaces where children and young people learn about native species, biodiversity, and the importance of conserving ecosystems that sustain community life.',
  'Liderazgo para un futuro sostenible': 'Leadership for a sustainable future',
  'Fortalecer estas iniciativas significa reconocer el liderazgo de las mujeres y acompañar sus propuestas con recursos, formación y redes de colaboración.': 'Strengthening these initiatives means recognizing women’s leadership and supporting their proposals with resources, training, and collaborative networks.',
  'Cuando el conocimiento local ocupa un lugar central, las soluciones se adaptan mejor a las necesidades de cada comunidad y tienen más posibilidades de mantenerse en el tiempo.': 'When local knowledge is central, solutions better meet each community’s needs and are more likely to last.',
  'La prevención de la anemia infantil requiere acompañamiento cercano, información clara y trabajo coordinado con las familias y los servicios de salud locales.': 'Preventing childhood anemia requires close support, clear information, and coordination with families and local health services.',
  'Acompañamiento cercano a las familias': 'Close support for families',
  'Las jornadas comunitarias acercan orientación y seguimiento a las familias, con especial atención al bienestar de niñas y niños. Los espacios de conversación ayudan a resolver dudas y a reconocer señales que requieren consulta profesional.': 'Community events provide guidance and follow-up for families, with special attention to children’s well-being. Conversations help answer questions and identify signs that need professional care.',
  'El trabajo conjunto con agentes locales facilita que la información responda a la realidad de cada comunidad y que las familias sepan dónde encontrar apoyo.': 'Working with local health workers helps ensure information reflects each community’s reality and families know where to find support.',
  'Hábitos saludables y continuidad': 'Healthy habits and continued care',
  'La alimentación variada, los controles periódicos y la orientación del personal de salud son parte importante de la prevención. Cada familia necesita información práctica y acompañamiento constante para incorporar estos hábitos.': 'A varied diet, regular checkups, and guidance from health professionals are important parts of prevention. Families need practical information and ongoing support to build these habits.',
  'Sembrando Perú continúa articulando acciones educativas y comunitarias que contribuyen a una infancia más saludable y a mejores oportunidades para el futuro.': 'Sembrando Perú continues to coordinate educational and community initiatives that support healthier childhoods and better opportunities for the future.',
  '"Historias que inspiran, acciones que transforman"': '"Stories that inspire, actions that transform"',
}

type LanguageContextValue = {
  language: Language
  toggleLanguage: () => void
  t: (text: string) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

function initialLanguage(): Language {
  if (typeof window === 'undefined') return 'es'
  return window.localStorage.getItem('sembrando-language') === 'en' ? 'en' : 'es'
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(initialLanguage)

  useEffect(() => {
    window.localStorage.setItem('sembrando-language', language)
    document.documentElement.lang = language
  }, [language])

  function toggleLanguage() {
    setLanguage((currentLanguage) => currentLanguage === 'es' ? 'en' : 'es')
  }

  function t(text: string) {
    return language === 'en' ? translations[text] ?? text : text
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}